site_name: Ivica Janekovic
docs_dir: docs/
site_dir: site/

repo_url: https://github.com/ivicajan/ivicajan.github.io

nav:
- Home: 'index.md'
- Publications: 'Publications.md'
- CV: 'CV.md'
- Projects: 'Projects.md'
- Research: 'Research.md'


theme: 
      name: spacelab
      colorscheme: github
      analytics:
        gtag: UA-136950400-2
